CREATE TABLE TELEFONE(
IDTELEFONE UNIQUEIDENTIFIER NOT NULL,
NUMERO NVARCHAR(11) NOT NULL,
IDCONTATO UNIQUEIDENTIFIER NOT NULL,
PRIMARY KEY(IDTELEFONE),
FOREIGN KEY(IDCONTATO) REFERENCES CONTATO(IDCONTATO))
GO

CREATE TABLE CONTATO(
IDCONTATO UNIQUEIDENTIFIER NOT NULL,
NOME NVARCHAR(150) NOT NULL,
PRIMARY KEY(IDCONTATO))
GO